version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: discord.js
    versions:
    - 12.5.2
  - dependency-name: discord-giveaways
    versions:
    - 4.4.3
